# Generated by Django 5.1.5 on 2026-02-16 19:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_itemservico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('nao_pago', 'Não pago'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='nao_pago', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PagamentoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartao)'), ('conta_movel', 'Conta Movel'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('outro', 'Outro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=80, null=True)),
                ('pago_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.pedido')),
            ],
            options={
                'ordering': ['-pago_em'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartao)'), ('conta_movel', 'Conta Movel'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('outro', 'Outro')], max_length=20)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='core.pagamentopedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='core.pedido')),
            ],
        ),
    ]
