# Generated by Django 5.1.5 on 2026-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reconcile_production_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('completo', 'Completo'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
