# Generated by Django 5.1.5 on 2026-02-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pontos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovimentacaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganho', 'Ganho'), ('uso', 'Uso'), ('expiracao', 'Expiração'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('pontos', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_pontos', to='core.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
            ],
        ),
    ]
