# Generated by Django 5.1.5 on 2026-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_pontos_movimentacaopontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentopedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartao)'), ('conta_movel', 'Conta Movel'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('pontos', 'Pontos Fidelidade'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartao)'), ('conta_movel', 'Conta Movel'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('pontos', 'Pontos Fidelidade'), ('outro', 'Outro')], max_length=20),
        ),
    ]
