# Generated by Django 5.1.5 on 2026-02-28 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pagamentopedido_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
