# Generated by Django 5.1.5 on 2026-02-28 05:07

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_pedido_total_pago_pedido_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentopedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerário'), ('pos', 'POS (Cartão)'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('conta_movel', 'Conta Móvel'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerário'), ('pos', 'POS (Cartão)'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('conta_movel', 'Conta Móvel'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20),
        ),
    ]
