# Generated by Django 5.1.5 on 2026-02-28 05:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pagamentopedido_criado_em_pedido_total_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='total_gasto_acumulado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gasto acumulado para controle de descontos de fidelidade', max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_marco_desconto',
            field=models.PositiveIntegerField(default=0, help_text='Último múltiplo de 5000 Mts que gerou desconto'),
        ),
    ]
