# Generated by Django 5.1.5 on 2026-02-28 13:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente_total_gasto_acumulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cabides_trazidos',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de cabides trazidos pelo cliente (mínimo 20 para desconto)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto_cabides',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado por cabides (140 Mts por 20 cabides)', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto_cabides_aplicado',
            field=models.BooleanField(default=False, help_text='Indica se o desconto por cabides já foi aplicado'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartão)'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('conta_movel', 'Conta Movel'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerario'), ('pos', 'POS (Cartão)'), ('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('conta_movel', 'Conta Movel'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20),
        ),
    ]
