# Generated by Django 5.1.5 on 2026-03-10 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pedido_cabides_trazidos_pedido_desconto_cabides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='desconto_cabides_aplicado',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cabides_trazidos',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de cabides trazidos pelo cliente (cada 20 cabides = 140 Mts de desconto)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='desconto_cabides',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado por cabides (140 Mts por cada 20 cabides)', max_digits=10),
        ),
    ]
