# Generated by Django 5.1.5 on 2026-05-27 03:45

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_pedido_desconto_cabides_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pontos',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='total_gasto_acumulado',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Total gasto acumulado para controle de descontos de fidelidade', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='core_client_nome_bfa2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefone'], name='core_client_telefon_eb9bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['pontos'], name='core_client_pontos_4f62c5_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['criado_em'], name='core_client_criado__5e2a16_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['total_gasto_acumulado'], name='core_client_total_g_c28b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome', 'pontos'], name='core_client_nome_08bd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['criado_em', 'pontos'], name='core_client_criado__b6a30e_idx'),
        ),
    ]
