# Generated by Django 5.1.5 on 2026-06-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cliente_options_cliente_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nivel_acesso',
            field=models.PositiveSmallIntegerField(default=1, help_text='1=Vendedor, 2=Gerente, 3=Admin, 4=SuperUser'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='grupo',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('gerente', 'Gerente'), ('admin', 'Admin'), ('superuser', 'SuperUser')], default='vendedor', help_text='Define o nível de acesso do funcionário.', max_length=20),
        ),
    ]
